// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvbCasuOCYg82zCnoI7GKp_kqOFUKVn3o',
    appId: '1:666375399338:web:f025275128ee0034f7edd3',
    messagingSenderId: '666375399338',
    projectId: 'controlasistenciaapp-d8e56',
    authDomain: 'controlasistenciaapp-d8e56.firebaseapp.com',
    storageBucket: 'controlasistenciaapp-d8e56.firebasestorage.app',
    measurementId: 'G-B7MKKCRVM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOMzLoFVubuLCzx_6AX7zOVWTflpg-pcs',
    appId: '1:666375399338:android:7e0dbee507606421f7edd3',
    messagingSenderId: '666375399338',
    projectId: 'controlasistenciaapp-d8e56',
    storageBucket: 'controlasistenciaapp-d8e56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVPvD7PK80y5UIAGV65h5u5q4Efm6CuUA',
    appId: '1:666375399338:ios:1f0c06ac37bea563f7edd3',
    messagingSenderId: '666375399338',
    projectId: 'controlasistenciaapp-d8e56',
    storageBucket: 'controlasistenciaapp-d8e56.firebasestorage.app',
    iosBundleId: 'com.example.appControlAsistencia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVPvD7PK80y5UIAGV65h5u5q4Efm6CuUA',
    appId: '1:666375399338:ios:1f0c06ac37bea563f7edd3',
    messagingSenderId: '666375399338',
    projectId: 'controlasistenciaapp-d8e56',
    storageBucket: 'controlasistenciaapp-d8e56.firebasestorage.app',
    iosBundleId: 'com.example.appControlAsistencia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvbCasuOCYg82zCnoI7GKp_kqOFUKVn3o',
    appId: '1:666375399338:web:441601e8e65714b9f7edd3',
    messagingSenderId: '666375399338',
    projectId: 'controlasistenciaapp-d8e56',
    authDomain: 'controlasistenciaapp-d8e56.firebaseapp.com',
    storageBucket: 'controlasistenciaapp-d8e56.firebasestorage.app',
    measurementId: 'G-1WKN36V47B',
  );
}
